### PR TITLE
N1984/Mags/Combats

### PR DESCRIPTION
**Pull request by KillerTheFlareon**
## Short description

Adding a couple of toys to secvend

## Why we need to add this

Just giving secvend more utility so it's not just "funny stunbaton" dispenser. There's other ideas as well in my thread (such as faster cuffing cuffs, golden MK and a sec-cape, but I cannot sprite any of that.)

As for balance I don't think it'll change too much, the n1984s are limited to 3 to prevent just everyone in sec having one, and combats are 2 (as they're basically security insuls). I made sure there was plenty of .45 mags as the sectech cannot fabricate them, therefore if someone loses/drops their mag it's basically gone forever.

## Media (Video/Screenshots)

https://github.com/user-attachments/assets/09b4a1b3-7472-4e99-98c2-51bc13536e0c

## Checks

- [x] I do not require assistance to complete the PR.
- [x] Before posting/requesting review of a PR, I have verified that the changes work.
- [x] I have added screenshots/videos of the changes, or this PR does not change in-game mechanics.
- [x] I affirm that my changes are licensed under the [Starlight Fork License](https://github.com/ss14Starlight/space-station-14/blob/Starlight/LICENSE-Starlight.TXT) and grant permission for use in this repository under its conditions.

**Changelog**

### CODE REVIEW

**Review by fqqf — CHANGES_REQUESTED** [review]
pretty sure its easy abusable considering it comes with 7 real .45 magnum bullets, and costs only 600
image


same goes for combat gloves.

These are supposed to be just trinkets not really give any big advantage, but here it just basically breaks whole sec department

**Comment by KillerTheFlareon** [comment]
> pretty sure its easy abusable considering it comes with 7 real .45 magnum bullets, and costs only 600 image
> 
> same goes for combat gloves.
> 
> These are supposed to be just trinkets not really give any big advantage, but here it just basically breaks whole sec department

Unfortunately there is no "empty" N1987 otherwise it wouldn't come with real bullets. I honestly don't know what to put for a price so I'm open to suggestions here
As for the combats..eh, not really? You can just go ask engineering for insuls or find them in maints and you'd have the same thing

**Comment by Clone0401** [comment]
Looking at the gun YML you should just be able to make a new n1984 prototype just use removing the starting items from gun_chamber and gun_magazine

**Comment by KillerTheFlareon** [comment]
It was simple enough to do (Haven't pushed an update yet however) but since I needed to now rename the gun to prevent duplication, would it effect balance too much to modify the gun to accept both .35 and .45? (Flavored as a modified N1984 for security use)

**Comment by Clone0401** [comment]
I think it would be best not to as it would be the only gun with multi ammo capabilities, and if we were to get a gun with multi ammo capabilities, I feel it should be more special that just something you buy at a vender

**Comment by KillerTheFlareon** [comment]
Fair enough.

**Comment by KillerTheFlareon** [comment]
> Fair enough.

Gun now comes out of the vending machine without a magazine nor a bullet in the chamber to prevent any sort of abuse whatsoever. Assuming each gun is taken, that's 2 mags per gun, which is the same as the MK for a total price of 800.

**Comment by Rinary1** [comment]
Thanks for your first PR, but the weapons you add to the vending machine will not be accepted, due to the fact that it violates the concept of gun control at security. Also the weapons you are adding are designed for central command and nt only. Likewise, the combat gloves are syndicate equipment.

**Pull request closed without merging**
