### PR TITLE
[Port] Vent crawling

### PR DESCRIPTION
**Pull request by Rinary1**
## Short description

Adds vent crawling for small beings.

AUTHOR OF THIS MECHANIC: https://github.com/space-wizards/space-station-14/pull/18182 .

This port is made with the author's permission.

## Media (Video/Screenshots)

https://cdn.discordapp.com/attachments/1274328216768872470/1308086660344447019/unknown_2024.11.18-17.04_1.mp4?ex=673caa22&is=673b58a2&hm=fb9edbaf85e10704c7d7a88bce4ab2f73b47d8f97725eea85a2a322332c2a7c7&

## Checks

- [x] I do not require assistance to complete the PR.
- [x] Before posting/requesting review of a PR, I have verified that the changes work.
- [x] I have added screenshots/videos of the changes, or this PR does not change in-game mechanics.
- [x] My changes are not licensed in any way.

**Changelog**

:cl: VigersRay
- add: Added vent. crawling for small beings.

:cl: Rinary
- tweak: Refactored vent crawling to new game version.
- add: Added abductor's vent gland(Allows to crawling in vents).
- add: Added contortionist's jumpsuit for atmosian uplink(Allows to crawling in vents).

### CODE REVIEW

**Review by Rinary1 — COMMENTED** [review]
seems be done.

**Review by StarlightHost — APPROVED** [review]

**Comment by formlessnameless** [comment]
Hey, I was looking into porting VigersRay's version of this for a different fork and saw this PR referenced on the original. Do you mind if I port your work to the fork I'm working on?

**Comment by Rinary1** [comment]
> Hey, I was looking into porting VigersRay's version of this for a different fork and saw this PR referenced on the original. Do you mind if I port your work to the fork I'm working on?

You can take my port, but, we have own licence with their requirements

**Comment by formlessnameless** [comment]
> You can take my port, but, we have own licence with their requirements

Alright, great! Thank you. I had some questions about the license but it looks like it's been updated so I think I've got enough of an understanding to move forward. Would it be sufficient to have something like "Initial file ported from the Starlight project repo, located at https://github.com/ss14Starlight/space-station-14" at the top of each ported file?

**Comment by Rinary1** [comment]
> > You can take my port, but, we have own licence with their requirements
> 
> Alright, great! Thank you. I had some questions about the license but it looks like it's been updated so I think I've got enough of an understanding to move forward. Would it be sufficient to have something like "Initial file ported from the Starlight project repo, located at https://github.com/ss14Starlight/space-station-14" at the top of each ported file?

yes

**Pull request merged**
