### PR TITLE
Resprite some walls and floors

### PR DESCRIPTION
**Pull request by fqqf**
## Description
resprite with Ko4erga, Morb0 and KREKS versions of tg (CC-BY-SA-3.0)
Why?  I genuinely believe they look better

## Before
image

## After
image

## Checks

- [x] I do not require assistance to complete the PR.
- [x] Before posting/requesting review of a PR, I have verified that the changes work.
- [x] I have added screenshots/videos of the changes, or this PR does not change in-game mechanics.
- [x] I affirm that my changes are licensed under the [Starlight Fork License](https://github.com/ss14Starlight/space-station-14/blob/Starlight/LICENSE-Starlight.TXT) and grant permission for use in this repository under its conditions.

**Changelog**

:cl: Miracula
- tweak: Resprite some walls and floors

### CODE REVIEW

**Comment by Rinary1** [comment]
No corvax, we get sprites from paradise station(SS13) or we could make our own

**Comment by fqqf** [comment]
> No corvax, we get sprites from paradise station(SS13) or we could make our own

whats wrong with corvax though?

**Comment by Clone0401** [comment]
idunno, i don't personally really like the isometric sprites that places like TG have.
it just looks... off... especially with how we don't have directional wall mounted things (EX: you can only see an APC from one direction)

**Comment by Rinary1** [comment]
> > No corvax, we get sprites from paradise station(SS13) or we could make our own
> 
> whats wrong with corvax though?

In that it's a different project, especially a Russian one.

**Comment by Rinary1** [comment]
closed, for the reason: not interested in use sprites of another project ss14, in the future plans to take sprites from Paradise Station or draw their own.

**Pull request closed without merging**
