### PR TITLE
Silicon law 0

### PR DESCRIPTION
**Pull request by Clone0401**
## Short description
Gives cyborgs a law 0 that makes them follow the AI's orders.
the previously 0th law given from the emag has been moved to the -1th place to not conflict with the new law 0

## Why we need to add this
discord discussion about it: https://discord.com/channels/1272545509562777621/1316941438914789406
i thought might as well make the PR for it

## Media (Video/Screenshots)
FjqcTHZnFz

https://github.com/user-attachments/assets/a994c1ff-6d54-4881-87e0-d8daf0088cc9
https://youtu.be/vDq4PAM6YR8 (video showing the AI isn't effected)

## Checks
- [X] I do not require assistance to complete the PR.
- [X] Before posting/requesting review of a PR, I have verified that the changes work.
- [X] I have added screenshots/videos of the changes, or this PR does not change in-game mechanics.
- [X] I affirm that my changes are licensed under the [Starlight Fork License](https://github.com/ss14Starlight/space-station-14/blob/Starlight/LICENSE-Starlight.TXT) and grant permission for use in this repository under its conditions.

**Changelog**
:cl: Clone0401
- tweak: Cyborgs now have a law 0 requiring them to follow AI orders

### CODE REVIEW

**Review by Rinary1 — CHANGES_REQUESTED** [review]
The emag law need to replace law 0 insted of adding -1 law, bevause it creates problem when ai can stop's emagged borgs

**Comment by Clone0401** [comment]
It’ll be a few days till I’ll be able to fix this. Just because I’ll be away.

**Comment by Clone0401** [comment]
> The emag law need to replace law 0 insted of adding -1 law, bevause it creates problem when ai can stop's emagged borgs

First, when I get back I’m going to move everything up one law because it looks weird.
And second, I didn’t want to replace the AI law because I fully well know that the crew will ask the Borgs to state all 4 laws, including the AI law. And if the AI law gets replaced, the crew will get suspicious and ask for the Borg’s laws to be fixed. Unless that is something that is wanted.
Along with that, due to one of my screenshots showing that the AI is mentioned In the Emag’d Borg’s lawset, the ai shouldn’t be able to orderEmagged Borgs.

**Comment by Clone0401** [comment]
alright so, it doesn't seem like there is anything wrong with how i implimented this. 
image
the -1th law defines who crew and ai are being the borg's emagger, so i don't see any issue.
and second, i'm not going to move up each law by 1 number because if i did that, with how i added this, the AI's laws would start on law 2, and not law 1 which does not make sense

**Pull request merged**
