### PR TITLE
More markings for Vulpkanin

### PR DESCRIPTION
**Pull request by JohnDWolfe**
## Short description
Porting over additional markings for Vulpkanin from SS13, using https://github.com/FluffiestFloof as a reference with edited textures where needed for the different legs and feet.

## Why we need to add this
More markings is awesome 😀

## Media (Video/Screenshots)
image
image

## Checks

- [✓] I do not require assistance to complete the PR.
- [✓] Before posting/requesting review of a PR, I have verified that the changes work.
- [✓] I have added screenshots/videos of the changes, or this PR does not change in-game mechanics.
- [✓] I affirm that my changes are licensed under the [Starlight Fork License](https://github.com/ss14Starlight/space-station-14/blob/Starlight/LICENSE-Starlight.TXT) and grant permission for use in this repository under its conditions.

**Changelog**

:cl: GnarlyGnoll
- add: More markings for Vulpkanin

### CODE REVIEW

**Comment by fqqf** [comment]
less go gamers

**Comment by fqqf** [comment]
if ya could also fix n return buggy paw socks from #111 it would be awesome

**Comment by JohnDWolfe** [comment]
> if ya could also fix n return buggy paw socks from #111 it would be awesome

i've got them split up here for arms/legs/hands/feet markings and stuff **but** idk if it'd merge right since this pr has the markings files saying I deleted all of it and THEN readded it all,
so i'm not sure if i made another pr at this exact moment if itd conflict with this one for whatever reason (lmk if not im not too good with github and stuff)
otherwise, i'll wait to see what goes on with this one 👍

**Comment by JohnDWolfe** [comment]
you know what, I just noticed some of the snout markings don't line up perfectly since the snouts are shorter on starlight
ima fix those and then also just make a new pr including the pawsocks markings fixed anyways 👍

**Pull request closed without merging**
