### PR TITLE
Add vulpkanins!

### PR DESCRIPTION
**Pull request by fqqf**
## Short description
imageimageimageimageimage

https://github.com/user-attachments/assets/489c029c-1f63-45be-8642-add8cdf4dfb6

image

Vulpkanin!

- I'll use corvax vulps (CC-BY-SA-3.0) since i find theirs to be the most beautiful ones, and also they can wag their tail 

## Checks

- [x] I do not require assistance to complete the PR.
- [x] Before posting/requesting review of a PR, I have verified that the changes work.
- [x] I have added screenshots/videos of the changes, or this PR does not change in-game mechanics.
- [x] I affirm that my changes are licensed under the [Starlight Fork License](https://github.com/ss14Starlight/space-station-14/blob/Starlight/LICENSE-Starlight.TXT) and grant permission for use in this repository under its conditions.

**Changelog**

:cl: Miracula
- add: Added vulpkanins

### CODE REVIEW

**Comment by fqqf** [comment]
will start working on it in a few weeks or so

**Comment by fqqf** [comment]
moved species_weights out of starlights due to vanilla problems with that yml that doesnt allow dublicates

**Comment by fqqf** [comment]
ffs i forgot to translate guidebook (btw i wrote it myself in russian for other server)

**Comment by fqqf** [comment]
image
less go gamers

**Comment by fqqf** [comment]
even though it displays it like this in editor:
image
its fine in game:
image

**Comment by fqqf** [comment]
ready for review

**Review by Rinary1 — APPROVED** [review]
needs fix displacement, i fix it myself later

**Pull request merged**
