### PR TITLE
Turn brigBuddy to pAI alternative for a brigmedic

### PR DESCRIPTION
**Pull request by fqqf**
## Checks

- [ ] I do not require assistance to complete the PR.
- [ ] Before posting/requesting review of a PR, I have verified that the changes work.
- [ ] I have added screenshots/videos of the changes, or this PR does not change in-game mechanics.
- [ ] I affirm that my changes are licensed under the [Starlight Fork License](https://github.com/ss14Starlight/space-station-14/blob/Starlight/LICENSE-Starlight.TXT) and grant permission for use in this repository under its conditions.

**Changelog**

### CODE REVIEW

**Comment by fqqf** [comment]
thinking of it being like a pAI with brigbuddy map.

At the other hand, would brigbuddy using itself drain battery? I am pretty sure it should

**Comment by KillerTheFlareon** [comment]
> thinking of it being like a pAI with brigbuddy map.
> 
> At the other hand, would brigbuddy using itself drain battery? I am pretty sure it should

Having the brigbuddy passively drain battery is going to lead to a situation where the battery is going to stay out of it until it needs to be used to check on things, then removed again. Very annoying to open up something only to find the battery is flat on it because it just drains

**Comment by fqqf** [comment]
> 
> Having the brigbuddy passively drain battery is going to lead to a situation where the battery is going to stay out of it until it needs to be used to check on things, then removed again. Very annoying to open up something only to find the battery is flat on it because it just drains

Not meaning passively, i mean if player playing as ghost role of brigbuddy opens map, should it drain battery as well? 

That's kind of a dilemma for me right now

--------

Maybe it would be best if ghost role of brigbuddy  wouldnt drain battery while using map, only user using brigbuddy would, which would encourage communication between brigbuddy user and brigbuddy itself

**Comment by fqqf** [comment]
will probably close this for now, because trashy idea

**Pull request closed without merging**
